src/Entity/MatchDay.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MatchDayRepository")
 */
class MatchDay
{
  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="integer")
   */
  private $number;

  /**
   * @ORM\Column(type="date")
   */
  private $match_date;

  /**
   * @ORM\Column(type="float", nullable=true)
   */
  private $result;

  /**
   * @ORM\Column(type="float", nullable=true)
   */
  private $best_result;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $url;

  /**
   * @ORM\OneToMany(targetEntity="App\Entity\PlayerVote", mappedBy="match_day", orphanRemoval=true)
   */
  private $playerVotes;

  /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Season", inversedBy="matchDays")
     * @ORM\JoinColumn(nullable=false)
     */
  private $season;

  public function __construct()
  {
    $this->playerVotes = new ArrayCollection();
  }

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getNumber(): ?int
  {
    return $this->number;
  }

  public function setNumber(int $number): self
  {
    $this->number = $number;

    return $this;
  }

  public function getMatchDate(): ?\DateTimeInterface
  {
    return $this->match_date;
  }

  public function setMatchDate(\DateTimeInterface $match_date): self
  {
    $this->match_date = $match_date;

    return $this;
  }

  public function getResult(): ?float
  {
    return $this->result;
  }

  public function setResult(?float $result): self
  {
    $this->result = $result;

    return $this;
  }

  public function getBestResult(): ?float
  {
    return $this->best_result;
  }

  public function setBestResult(?float $best_result): self
  {
    $this->best_result = $best_result;

    return $this;
  }

  /**
   * @return string
   */
  public function getUrl(): string
  {
    return $this->url;
  }

  /**
   * @param string $url
   */
  public function setUrl(string $url): self
  {
    $this->url = $url;
    return $this;
  }

  /**
   * @return Collection|PlayerVote[]
   */
  public function getPlayerVotes(): Collection
  {
    return $this->playerVotes;
  }

  public function addPlayerVote(PlayerVote $playerVote): self
  {
    if (!$this->playerVotes->contains($playerVote)) {
      $this->playerVotes[] = $playerVote;
      $playerVote->setMatchDay($this);
      return $this;
    }

    return $this;
  }

  public function removePlayerVote(PlayerVote $playerVote): self
  {
    if ($this->playerVotes->contains($playerVote)) {
      $this->playerVotes->removeElement($playerVote);
      // set the owning side to null (unless already changed)
      if ($playerVote->getMatchDay() === $this) {
        $playerVote->setMatchDay(null);
      }
    }

    return $this;
  }

  /**
   * @param Player $player
   * @return PlayerVote
   */
  public function getVoteFor(Player $player): PlayerVote
  {
    foreach ($this->playerVotes as $playerVote) {
      /* @var \App\Entity\PlayerVote $playerVote */
      if ($playerVote->getPlayer() == $player) {
        return $playerVote;
      }
    }

    return new PlayerVote();
  }

  public function getDifference(): ?float
  {
    return round($this->best_result - $this->result, 2);
  }
}

src/Form/MatchDayType.php
<?php

namespace App\Form;

use App\Entity\MatchDay;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatchDayType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
      ->add('number', IntegerType::class)
      ->add('match_date', DateType::class, [
        'widget' => 'single_text',])
      ->add('url', TextType::class);
  }

  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults([
      'data_class' => MatchDay::class,
    ]);
  }
}

src/Controller/MatchDayController.php
<?php

namespace App\Controller;

use App\Entity\MatchDay;
use App\Form\MatchDayType;
use App\Service\MatchDayScraperInterface;
use App\Service\MatchDayCalculator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MatchDayController extends AbstractController
{
  /**
   * @Route("/matchday/show/{match_day_number}", name="matchday_show", methods={"GET"})
   */
  public function show(Request $request, int $match_day_number, EntityManagerInterface $em, MatchDayCalculator $calculator): Response
  {
    $match_day_repo = $em->getRepository(MatchDay::class);
    $match_day      = $match_day_repo->findOneBy(['number' => $match_day_number]);
    if (!$match_day) {
      $match_day      = new MatchDay();
      $match_day->setNumber($match_day_number);
      $em->persist($match_day);
    }

    $selected_list = $calculator->getSelectedPlayersOrderByRole($match_day);
    $selected_bench_list = $calculator->getSelectedBenchPlayers($match_day);
    $best_list = $calculator->getBestPlayersOrderByRole($match_day);
    $best_bench_list = $calculator->getBestBenchPlayers($match_day);

    return $this->render('match_day/show.html.twig', [
      'match_day' => $match_day,
      'selected_list' => $selected_list,
      'selected_bench_list' => $selected_bench_list,
      'best_list' => $best_list,
      'best_bench_list' => $best_bench_list,
    ]);
  }
  /**
   * @Route("/matchday/edit/{match_day_number}", name="matchday_edit", methods={"GET","POST"})
   */
  public function edit(Request $request, int $match_day_number, EntityManagerInterface $em, MatchDayScraperInterface $scraper, MatchDayCalculator $calculator): Response
  {
    $match_day_repo = $em->getRepository(MatchDay::class);
    $match_day      = $match_day_repo->findOneBy(['number' => $match_day_number]);
    if (!$match_day) {
      $match_day      = new MatchDay();
      $match_day->setNumber($match_day_number);
      $em->persist($match_day);
    }

    $form = $this->createForm(MatchDayType::class, $match_day);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $em->flush();
      $scraper->scrape($match_day);
      $calculator->calculateResults($match_day);

      return $this->redirectToRoute('home');
    }

    return $this->render('match_day/edit.html.twig', [
      'match_day' => $match_day,
      'form'      => $form->createView(),
    ]);
  }
}

templates/match_day/_form.html.twig
{{ form_start(form) }}
    <div>
        {{ form_widget(form) }}
    </div>
    <div>
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/match_day/_lineup.html.twig
<table class="table table-hover">
    <thead class="thead-light">
    <tr>
        <th>Role</th>
        <th>Name</th>
        <th>Vote</th>
    </tr>
    </thead>
    <tbody>
    {% set role = '' %}
    {% for player_vote in player_list %}
        {% set best_not_selected = highlight_best and (player_vote.getBest() and not player_vote.getSelected()) %}
        <tr class="player-role role-{{ player_vote.player.role|lower }} {% if role != player_vote.player.role %} role-first {% endif %} {% if best_not_selected == true %} best {% endif %}" >
            <td>{{ player_vote.player.role }}</td>
            <td>{{ player_vote.player.name }}</td>
            <td class="">
                {{ match_day.getVoteFor(player_vote.player).getVote() }}
            </td>
        </tr>
        {% set role = player_vote.player.role %}
    {% endfor %}
    </tbody>
    <tfoot class="totals">
        <tr>
            <td colspan="2">{{ total_label }}</td>
            <td>{{ total_value }}</td>
        </tr>
    </tfoot>
</table>

<table class="table table-hover">
    
    <tbody>
    {% for player_vote in bench_list %}
        <tr class="" >
            <td>{{ player_vote.player.role }}</td>
            <td>{{ player_vote.player.name }}</td>
            <td class="">
                {{ match_day.getVoteFor(player_vote.player).getVote() }}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/match_day/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MatchDay{% endblock %}

{% block body %}
    <h1>Edit MatchDay</h1>

    {{ include('match_day/_form.html.twig', {'button_label': 'Update'}) }}
    
    <a class="btn btn-secondary mt-1" href="{{ path('home') }}">back to home</a>

{% endblock %}

templates/match_day/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Match {{ match_day.number }}{% endblock %}

{% block body %}

<div class="example-wrapper">
    <div class="mb-2">
        <h2>Match {{ match_day.number }} - {{ match_day.matchDate|date }}</h2>
        <a class="btn btn-primary mt-1" href="{{ path('matchday_edit', { match_day_number: match_day.number }) }}">Edit Match Day info</a>
        <a class="btn btn-secondary mt-1" href="{{ path('home') }}">Back to list</a>
    </div>

    <div class="float-none">
        <div class="col-sm-5 float-left">
            {{ include('match_day/_lineup.html.twig', {'player_list': selected_list, 'bench_list': selected_bench_list, 'total_label': 'Reale', 'total_value': match_day.getResult(), 'highlight_best': false}) }}
        </div>



        <div class="col-sm-5 float-right">
            {{ include('match_day/_lineup.html.twig', {'player_list': best_list, 'bench_list': best_bench_list, 'total_label': 'Massimo', 'total_value': match_day.getBestResult(), 'highlight_best': true}) }}
           
        </div>
    </div>
</div>
{% endblock %}